### ISSUE TITLE
Unable to install the plugin, AWS resource returning 403

### ISSUE THREAD

**Issue by jconcavi** [slavaGanzin/http2-server#6]
When installing the server with the command `npm install -g static-http2-server` I'm having the following error:

`node-pre-gyp ERR! Tried to download(403): https://node-zopfli.s3.amazonaws.com/Release/zopfli-v1.4.0-node-v64-win32-x64.tar.gz`
`node-pre-gyp ERR! Pre-built binaries not found for node-zopfli@1.4.0 and node@10.13.0 (node-v64 ABI, unknown) (falling back to source compile with node-gyp)`

**Comment by slavaGanzin** [comment]
This is not an error, it's just warning that zopfli will be compiled from source, because it doesn't find suitable binary distribution. 

As this is a problem with dependency and your setup I will close the issue. And forward you to issue in zopfli itself: https://github.com/pierreinglebert/node-zopfli/issues/79
